# Generated by Django 5.1.4 on 2025-03-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
