from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import *

# Create a router and register the viewsets
router = DefaultRouter()
router.register(r'rewards', RewardViewSet, basename='reward')

urlpatterns = [
    # Include the routes generated by the router for RewardViewSet
    path('', include(router.urls)),

    # Explicitly define the URLs for other views
    path('update-rewards-points/', UpdateRewardPointsView.as_view(),
         name='update-reward-points'),
    path('all-rewards', GetAllRewardsView.as_view(), name='all-rewards'),
    path('available-rewards/', GetAvailableRewardsView.as_view(),
         name='available-rewards'),
    path('redeem-reward/<int:reward_id>/',
         RedeemRewardView.as_view(), name='redeem-reward'),
]
