from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import *

# Create a router and register the viewsets
router = DefaultRouter()
router.register(r'rewards', RewardViewSet, basename='reward')

urlpatterns = [
    # Include the routes generated by the router for RewardViewSet
    path('', include(router.urls)),
    
    # admin
    path('manage-users/', ManageUserView.as_view(), name='manage-users'),
    path('user/<int:id>/change-role/',
         ChangeUserRoleView.as_view(), name='change-user-role'),
    path('user/<int:id>/delete/', RemoveUserView.as_view(), name='remove-user'),
    
    # user
    path('profile/', UserProfileView.as_view(), name='profile'),

    # Explicitly define the URLs for other views
    path('update-rewards-points/', UpdateRewardPointsView.as_view(),
         name='update-reward-points'),
    path('all-rewards', GetAllRewardsView.as_view(), name='all-rewards'),
    path('available-rewards/', GetAvailableRewardsView.as_view(),
         name='available-rewards'),
    path('redeem-reward/<int:reward_id>/',
         RedeemRewardView.as_view(), name='redeem-reward'),
]
