# Generated by Django 5.1.4 on 2025-02-23 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0002_alter_collectedwaste_collection_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='collector',
        ),
    ]
