# Generated by Django 5.1.4 on 2025-03-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0003_remove_report_collector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectedwaste',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('verified', 'Verified')], default='in_progress', max_length=20),
        ),
    ]
